apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "platerec-helm.fullname" . }}
  labels:
    {{- include "platerec-helm.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "platerec-helm.fullname" . }}
      labels:
        {{- include "platerec-helm.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
      - name: pre-delete-job
        image: busybox
        command: ['wget']
        args:  ['{{ include "platerec-helm.fullname" . }}:{{ .Values.service.port }}/uninstall/']