kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "platerec-helm.pvc.claimname" . }}
  labels:
    app: "{{ include "platerec-helm.fullname" . }}"
    chart: "{{ template "platerec-helm.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{ include "platerec-helm.storageClass" . }}
