apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platerec-helm.fullname" . }}-auth
  namespace: {{ $.Release.Namespace }}
data:
  TOKEN: {{ .Values.TOKEN | b64enc }}
  LICENSE_KEY: {{ .Values.LICENSE_KEY | b64enc }}
  